### ISSUE TITLE
Extension not resizing chatterino window to the desired space in Chrome

### ISSUE THREAD

**Issue by vaskezu** [fourtf/chatterino-browser-ext#2]
Using Chrome version Version 67.0.3396.87 (Official Build) (64-bit)
Windows 10 pro version 1803

Could be related to having the custom resolution scale set to - Custom 115 %

![extensionbug 1](https://user-images.githubusercontent.com/14653103/41818821-63a85db0-77b6-11e8-92f8-add37c1b4740.PNG)

![extensionbug 2](https://user-images.githubusercontent.com/14653103/41818822-63cb5b94-77b6-11e8-9b98-9ae954f33832.PNG)

**Comment by vaskezu** [comment]
Let me if I should post this on the chatterino 2 repo instead

**Comment by hzah1** [comment]
:) hi i just had an idea for ur next update in chatterino.  a feature that would allow u to minimize specific channels so you wouldnt see them in ur tab but they are still there in the backround and a button on maybe the top right that would expand & minimize it to what it is right now (for those who put alot of channels to farm gifted subs)  mine currently takes up half the screen LUL
